#!/bin/bash
if [ -d /sys/class/backlight/intel_backlight/brightness ]; then
    [ $(cat /sys/class/backlight/intel_backlight/brightness) -lt 94000 ] && echo $(($(cat /sys/class/backlight/intel_backlight/brightness)+5000)) > /sys/class/backlight/intel_backlight/brightness || tmux display-message "Max brightness reached!"
fi
